### ISSUE TITLE
What's the difference between observation (states) and starting states?

### ISSUE THREAD

**Issue by xuhuazhe** [nagaban2/nn_dynamics#2]
In your main.py, observations (states) is used to train the dyn_model. But there are other states which are the "starting states" that is not used.  For example, in a swimmer env, states are 16-dimensional vectors; however, starting states have 17 dims.

**Comment by anagabandi** [comment]
Sorry for the confusion in naming. States throughout the code generally represent "observations" (as returned by the env's get_observation function**), whereas starting_states represent the true "state" of the env. 

An example of when you might need the full true env state is if you'd like to visualize a rollout later (or reproduce something later), because you'll need to reset the env to this particular full state before executing your actions.

---------------------------------------- 

**Note: technically the env's observations go through my function from_observation_to_usablestate (in data_manipulation.py) before being used in the code. Because for example, instead of a 3x3rotation matrix (which is the obs that the env for ant gives you), you might want to calculate and use (roll, pitch, yaw) as inputs to the neural net.
